/** Common African markets — ISO 3166-1 alpha-2 + default ISO 4217 currency */
export const AFRICAN_COUNTRIES: { code: string; name: string; currency: string }[] = [
  { code: "NG", name: "Nigeria", currency: "NGN" },
  { code: "KE", name: "Kenya", currency: "KES" },
  { code: "ZA", name: "South Africa", currency: "ZAR" },
  { code: "GH", name: "Ghana", currency: "GHS" },
  { code: "EG", name: "Egypt", currency: "EGP" },
  { code: "MA", name: "Morocco", currency: "MAD" },
  { code: "SN", name: "Senegal", currency: "XOF" },
  { code: "CI", name: "Côte d'Ivoire", currency: "XOF" },
  { code: "RW", name: "Rwanda", currency: "RWF" },
  { code: "TZ", name: "Tanzania", currency: "TZS" },
  { code: "UG", name: "Uganda", currency: "UGX" },
  { code: "ZM", name: "Zambia", currency: "ZMW" },
  { code: "BW", name: "Botswana", currency: "BWP" },
  { code: "MU", name: "Mauritius", currency: "MUR" },
  { code: "ET", name: "Ethiopia", currency: "ETB" },
];

export const ISO_CURRENCIES = [
  "NGN",
  "KES",
  "ZAR",
  "GHS",
  "EGP",
  "MAD",
  "XOF",
  "XAF",
  "RWF",
  "TZS",
  "UGX",
  "ZMW",
  "BWP",
  "MUR",
  "ETB",
  "USD",
  "EUR",
  "GBP",
];
